# Generated by Django 5.2.6 on 2025-10-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping'), ('home', 'Home'), ('work', 'Work')], default='home', max_length=20),
        ),
    ]
