# Generated by Django 5.2.6 on 2025-10-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('home', 'Home'), ('billing', 'Billing'), ('work', 'Work')], default='home', max_length=20),
        ),
    ]
