# Generated by Django 5.2.3 on 2025-07-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', error_messages={'invalid_choice': 'Invalid status. Valid options are: pending, processing, shipped, completed, canceled'}, max_length=20),
        ),
    ]
